export const appTitle = 'Movie App';
export const appAuthor = 'Gillian Downey';
export const appStorageName = 'movie-app-favs';
export const nowPlaying = 'https://api.themoviedb.org/3/movie/now_playing?language=en-US&page=1';
export const popular = 'https://api.themoviedb.org/3/movie/popular?language=en-US&page=1';
export const topRated = 'https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1';
export const upcoming = 'https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1';
export const imageBaseURL = 'https://api.themoviedb.org/3/movie/movie_id/images';
export const apiKey = '0def3e9736e9a726d7587ac70c5d57d2';
export const baseURL = 'https://api.themoviedb.org/3';